# Generated by Django 6.0.3 on 2026-04-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_bill_submitted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='AIT'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='excluding_vat_ait',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT + AIT', max_digits=14, verbose_name='Total VAT & AIT'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='billingtaxsettings',
            name='ait_percent',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Default AIT % for new bills; each bill can use its own % on the bill form (0 if no AIT).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='billingtaxsettings',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Default VAT % for new bills; each bill can use its own % on the bill form (0 if no VAT).', max_digits=6),
        ),
    ]
