# Generated by GPT-5.2 on 2026-04-09

from django.db import migrations, models


def merge_duplicate_services(apps, schema_editor):
    Service = apps.get_model('clients', 'Service')

    # For existing data created under the old "one name per row" approach:
    # merge services that share the same agreement + type + charge + description
    # into a single Service row with multiple names (one per line).
    qs = Service.objects.all().order_by('agreement_id', 'service_type', 'charge', 'description', 'id')

    current_key = None
    keeper = None
    names = []

    def flush():
        nonlocal keeper, names
        if keeper is None:
            return
        merged = [n.strip() for n in names if n and n.strip()]
        keeper.name = "\n".join(merged) if merged else keeper.name
        keeper.save(update_fields=['name'])
        keeper = None
        names = []

    for s in qs.iterator():
        key = (s.agreement_id, s.service_type, str(s.charge), s.description or '')
        if current_key != key:
            flush()
            current_key = key
            keeper = s
            names = [(s.name or '').strip()]
        else:
            names.append((s.name or '').strip())
            # delete duplicates; keeper stays
            s.delete()

    flush()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_agreement_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.TextField(verbose_name='Service Name'),
        ),
        migrations.RunPython(merge_duplicate_services, migrations.RunPython.noop),
    ]

