# Generated by GPT-5.2 on 2026-04-10

from django.db import migrations, models


def backfill_short_form(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')

    def make_sf(name):
        parts = [p for p in (name or '').replace('&', ' ').replace('-', ' ').split() if p]
        if not parts:
            return ''
        # initials up to 6 chars
        sf = ''.join([p[0].upper() for p in parts])[:6]
        return sf

    for c in Client.objects.all().only('id', 'name', 'short_form'):
        if not (c.short_form or '').strip():
            c.short_form = make_sf(c.name)
            c.save(update_fields=['short_form'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_service_name_text_and_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='short_form',
            field=models.CharField(default='', max_length=50, verbose_name='Client Name Short Form'),
        ),
        migrations.RunPython(backfill_short_form, migrations.RunPython.noop),
    ]

