# Generated by Django 4.2.29 on 2026-03-30 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_client', models.BooleanField(default=False, verbose_name='Can Add Client')),
                ('can_edit_client', models.BooleanField(default=False, verbose_name='Can Edit Client')),
                ('can_delete_client', models.BooleanField(default=False, verbose_name='Can Delete Client')),
                ('can_generate_bill', models.BooleanField(default=False, verbose_name='Can Generate Bill')),
                ('can_edit_bill', models.BooleanField(default=False, verbose_name='Can Edit Bill')),
                ('can_delete_bill', models.BooleanField(default=False, verbose_name='Can Delete Bill')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Can View Reports')),
                ('can_export_reports', models.BooleanField(default=False, verbose_name='Can Export Reports')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
