# Generated by Django 6.0.3 on 2026-04-13 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_dashboard_workflow_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete', 'Delete')], db_index=True, max_length=32)),
                ('target_model', models.CharField(db_index=True, max_length=120, verbose_name='Object type')),
                ('object_pk', models.CharField(max_length=64, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
